#
# Product-specific compile-time definitions.
#

TARGET_BOARD_PLATFORM := imx31_3stack
TARGET_CPU_ABI := armeabi

TARGET_NO_BOOTLOADER := true
TARGET_NO_RECOVERY := false
TARGET_NO_KERNEL := true
TARGET_NO_RADIOIMAGE := true

TARGET_PROVIDES_INIT_RC := true

#BOARD_USES_GENERIC_AUDIO := true
BOARD_USES_ALSA_AUDIO := true

BOARD_HAVE_BLUETOOTH := true
#BOARD_GPS_LIBRARIES := libgps
USE_CAMERA_STUB := true
#BOARD_CAMERA_LIBRARIES := libcamera
BOARD_HAVE_VPU := false

BOARD_HAVE_WIFI := true
PREBUILT_CSR_UNIFI_WIFI := true

BOARD_SOC_TYPE := IMX31

HAVE_FSL_IMX_CODEC := true
PREBUILT_FSL_IMX_CODEC := true

TARGET_USERIMAGES_USE_UBIFS :=true
TARGET_MKUBIFS_ARGS := -m 2048 -e 129024 -c 2048 -x none
TARGET_MKUBIFS_ARGS_RECOVERY := -m 2048 -e 129024 -c 100 -x none
TARGET_UBIRAW_ARGS := -m 2048 -p 128KiB -s 512 -O 512 $(PRODUCT_OUT)/ubinize.ini
TARGET_UBIRAW_RECO_ARGS := -m 2048 -p 128KiB -s 512 -O 512 $(PRODUCT_OUT)/ubinize_reco.ini

TARGET_TS_CALIBRATION := true
TARGET_TS_DEVICE := "mxc_ts"

