#
# Product-specific compile-time definitions.
#

BOARD_GPS_LIBRARIES := libgps

BOARD_HAVE_WIFI_CSR := true
PREBUILT_CSR_UNIFI_WIFI := true

BOARD_SOC_CLASS := IMX5X
BOARD_SOC_TYPE := IMX51
BOARD_SOC_REV := TO2

BOARD_CAMERA_NV12 := true

TARGET_USERIMAGES_USE_UBIFS :=true
TARGET_MKUBIFS_ARGS := -m 4096 -e 516096 -c 4096 -x none
TARGET_MKUBIFS_ARGS_RECOVERY := -m 4096 -e 516096 -c 40 -x none
TARGET_UBIRAW_ARGS := -m 4096 -p 512KiB $(PRODUCT_OUT)/ubinize.ini
TARGET_UBIRAW_RECO_ARGS := -m 4096 -p 512KiB $(PRODUCT_OUT)/ubinize_reco.ini

TARGET_SELECT_KEY := 353

HAVE_FSL_IMX_GPU := true
HAVE_FSL_IMX_IPU := true
