#
# Product-specific compile-time definitions.
#

TARGET_BOARD_PLATFORM := imx37_3stack
TARGET_CPU_ABI := armeabi

TARGET_NO_BOOTLOADER := true
TARGET_NO_RECOVERY := true
TARGET_NO_KERNEL := true
TARGET_NO_RADIOIMAGE := true

TARGET_PROVIDES_INIT_RC := true

#BOARD_USES_GENERIC_AUDIO := true
BOARD_USES_ALSA_AUDIO := true

#BOARD_HAVE_BLUETOOTH := false

#BOARD_GPS_LIBRARIES := libgps

USE_CAMERA_STUB := true
#BOARD_CAMERA_LIBRARIES := libcamera

BOARD_HAVE_VPU := true
#BOARD_HAVE_WIFI := true

BOARD_SOC_TYPE := IMX37
BOARD_SOC_REV := TO1_1_1

TARGET_USERIMAGES_USE_UBIFS :=true
TARGET_MKUBIFS_ARGS := -m 4096 -e 1032192 -c 2048 -x none
TARGET_UBIRAW_ARGS := -m 4096 -p 512KiB $(PRODUCT_OUT)/ubinize.ini
