
add_lunch_combo imx6q_arm2-eng
add_lunch_combo imx6q_arm2-user
add_lunch_combo sabresd_6q-eng
add_lunch_combo sabresd_6q-user
add_lunch_combo sabresd_6dl-eng
add_lunch_combo sabresd_6dl-user
add_lunch_combo imx6q_sabreauto-eng
add_lunch_combo imx6q_sabreauto-user
add_lunch_combo sabrelite_6q-eng
add_lunch_combo sabrelite_6q-user
add_lunch_combo marsboard_6q-eng
add_lunch_combo marsboard_6q-user
